/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  ReentrantTreasuryTest,
  ReentrantTreasuryTestInterface,
} from "../ReentrantTreasuryTest";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "victim",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [],
    name: "HitFallback",
    type: "event",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506040516102fd3803806102fd83398181016040528101906100329190610126565b6100647f3f1849c448229dbcad6f33831ca862b34a7f35e9588949ab82aa183d93583de560001b61010e60201b60201c565b6100967f7d3d5b2c1f821c7f33cebabb5874585a22c9eb47f931cb3c5ec6a9b86410c51e60001b61010e60201b60201c565b6100c87ff2264e8537d7f2efa4ef39e90c1497b0472257b83c8bc2275b0fd822a5b5636c60001b61010e60201b60201c565b806000806101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff160217905550506101a1565b50565b6000815190506101208161018a565b92915050565b60006020828403121561013c5761013b610185565b5b600061014a84828501610111565b91505092915050565b600061015e82610165565b9050919050565b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b600080fd5b61019381610153565b811461019e57600080fd5b50565b61014d806101b06000396000f3fe60806040523661010f576100357ff62631f58aacb1ea117c32aea816fdb706f5f3a64d261d8f5cbc497d138c75a360001b610114565b7f7d5cd9daf528e533ba8cae574873331c202235d7f9a7748ed50410618a9544b060405160405180910390a161008d7f7102cc38616e9763a0f740a4ff91947ce4c4bebcf644a0f1a9676e572ed974e460001b610114565b60008054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16633ccfd60b6040518163ffffffff1660e01b8152600401600060405180830381600087803b1580156100f557600080fd5b505af1158015610109573d6000803e3d6000fd5b50505050005b600080fd5b5056fea26469706673582212209027fc44a6c434decaea85503bc74a164ab9a99f58f54be00f4629af36f5cc3564736f6c63430008070033";

type ReentrantTreasuryTestConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ReentrantTreasuryTestConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ReentrantTreasuryTest__factory extends ContractFactory {
  constructor(...args: ReentrantTreasuryTestConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
    this.contractName = "ReentrantTreasuryTest";
  }

  deploy(
    victim: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ReentrantTreasuryTest> {
    return super.deploy(
      victim,
      overrides || {}
    ) as Promise<ReentrantTreasuryTest>;
  }
  getDeployTransaction(
    victim: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(victim, overrides || {});
  }
  attach(address: string): ReentrantTreasuryTest {
    return super.attach(address) as ReentrantTreasuryTest;
  }
  connect(signer: Signer): ReentrantTreasuryTest__factory {
    return super.connect(signer) as ReentrantTreasuryTest__factory;
  }
  static readonly contractName: "ReentrantTreasuryTest";
  public readonly contractName: "ReentrantTreasuryTest";
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ReentrantTreasuryTestInterface {
    return new utils.Interface(_abi) as ReentrantTreasuryTestInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ReentrantTreasuryTest {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ReentrantTreasuryTest;
  }
}
