/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { BaseContract, Signer, utils } from "ethers";
import { EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface ReentrantTreasuryTestInterface extends utils.Interface {
  contractName: "ReentrantTreasuryTest";
  functions: {};

  events: {
    "HitFallback()": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "HitFallback"): EventFragment;
}

export type HitFallbackEvent = TypedEvent<[], {}>;

export type HitFallbackEventFilter = TypedEventFilter<HitFallbackEvent>;

export interface ReentrantTreasuryTest extends BaseContract {
  contractName: "ReentrantTreasuryTest";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ReentrantTreasuryTestInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {};

  callStatic: {};

  filters: {
    "HitFallback()"(): HitFallbackEventFilter;
    HitFallback(): HitFallbackEventFilter;
  };

  estimateGas: {};

  populateTransaction: {};
}
