/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as test from "./test";
export type { test };
export type { ERC721NonTransferable } from "./ERC721NonTransferable";
export type { ProofOfResidency } from "./ProofOfResidency";
