/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface ReentrantTreasuryTestInterface extends utils.Interface {
  functions: {
    "respondToChallenge(uint256,uint16,string)": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "respondToChallenge"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "respondToChallenge",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "respondToChallenge",
    data: BytesLike
  ): Result;

  events: {
    "HitFallback()": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "HitFallback"): EventFragment;
}

export interface HitFallbackEventObject {}
export type HitFallbackEvent = TypedEvent<[], HitFallbackEventObject>;

export type HitFallbackEventFilter = TypedEventFilter<HitFallbackEvent>;

export interface ReentrantTreasuryTest extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ReentrantTreasuryTestInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    respondToChallenge(
      tokenId: PromiseOrValue<BigNumberish>,
      country: PromiseOrValue<BigNumberish>,
      commitment: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  respondToChallenge(
    tokenId: PromiseOrValue<BigNumberish>,
    country: PromiseOrValue<BigNumberish>,
    commitment: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    respondToChallenge(
      tokenId: PromiseOrValue<BigNumberish>,
      country: PromiseOrValue<BigNumberish>,
      commitment: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {
    "HitFallback()"(): HitFallbackEventFilter;
    HitFallback(): HitFallbackEventFilter;
  };

  estimateGas: {
    respondToChallenge(
      tokenId: PromiseOrValue<BigNumberish>,
      country: PromiseOrValue<BigNumberish>,
      commitment: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    respondToChallenge(
      tokenId: PromiseOrValue<BigNumberish>,
      country: PromiseOrValue<BigNumberish>,
      commitment: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
