/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as test from "./test";
export { ERC721NonTransferable__factory } from "./ERC721NonTransferable__factory";
export { ProofOfResidency__factory } from "./ProofOfResidency__factory";
