name: contracts

on:
  push:
    branches:
      - "*"
    paths-ignore:
      - "packages/web/**"
  pull_request:
    branches:
      - "*"
    paths-ignore:
      - "packages/web/**"

defaults:
  run:
    working-directory: packages/contracts

jobs:
  test:
    name: Test Ubuntu with Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
      - name: Install
        run: yarn --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Run tests
        run: yarn test
        env:
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
