name: contracts

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"

defaults:
  run:
    working-directory: packages/contracts

jobs:
  test:
    name: Test Ubuntu with Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo snap install solc
          pip3 install slither-analyzer
      - name: Install
        run: yarn --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Run code analysis
        # this is dumb, but slither has a problem with yarn workspaces and it's not worth the time
        run: |
          cp -r ../../node_modules/@openzeppelin/ ./node_modules/@openzeppelin/
          yarn analyze

      - name: Run test coverage
        run: yarn coverage
        env:
          NEXT_PUBLIC_ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
      - name: Upload to codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          name: contracts # optional
          fail_ci_if_error: true
