name: contracts

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "packages/web/**"
  pull_request:
    branches:
      - "*"

defaults:
  run:
    working-directory: packages/contracts

jobs:
  test:
    name: Test Ubuntu with Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
      - name: Install
        run: yarn --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Run test coverage
        run: yarn coverage
        env:
          NEXT_PUBLIC_ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
      - name: Upload to codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          name: contracts # optional
          fail_ci_if_error: true
